AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Local API + indexer (SAM + LocalStack)

Globals:
  Function:
    Timeout: 10
    MemorySize: 256
    Architectures: [x86_64]
    Environment:
      Variables:
        DEV_BYPASS_AUTH: true
        AWS_REGION: us-east-1
        AWS_ENDPOINT_URL: http://localstack:4566
        S3_BUCKET: local-claims-bucket
        DDB_TABLE: local-claims-table
        PRESIGN_TTL_SECONDS: 300

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi

  PresignFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["bootstrap"]
      Events:
        PresignRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: POST
            Path: /claims/presign
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerBuildArgs: { TARGET: presign }

  ListFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["bootstrap"]
      Events:
        ListRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /claims
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerBuildArgs: { TARGET: list }

  IndexerFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["bootstrap"]
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerBuildArgs: { TARGET: indexer }
