AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Insurance Claim Upload Portal (local) – API + S3 indexer

Globals:
  Function:
    Timeout: 10
    MemorySize: 256
    PackageType: Image
    Architectures: [x86_64]
    Environment:
      Variables:
        AWS_REGION: us-east-1
        # Point SDKs to LocalStack at runtime (network alias below)
        AWS_ENDPOINT_URL: http://localstack:4566
        S3_BUCKET: local-claims-bucket
        DDB_TABLE: local-claims-table
        PRESIGN_TTL_SECONDS: 300
        DEV_BYPASS_AUTH: true

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi

  PresignFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        PresignRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: POST
            Path: /claims/presign
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerBuildArgs:
        TARGET: presign

  ListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ListRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /claims
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerBuildArgs:
        TARGET: list

  IndexerFunction:
    Type: AWS::Serverless::Function
    Properties:
      # No API event; this is S3-triggered in real infra.
      # In local dev, invoke with: sam local invoke IndexerFunction -e events/s3_put.json
      Events: {}
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerBuildArgs:
        TARGET: indexer
